//! # Trident Generated Types
//!
//! This file is automatically generated by Trident.
//! **DO NOT EDIT THIS FILE MANUALLY**

#![allow(dead_code)]
#![allow(unused_imports)]

use borsh::BorshDeserialize;
use borsh::BorshSerialize;
use trident_fuzz::fuzzing::*;

// ============================================================================
// PROGRAM MODULES
// ============================================================================

// ----------------------------------------------------------------------------
// Program: sss_transfer_hook
// ----------------------------------------------------------------------------
pub mod sss_transfer_hook {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_transfer_hook
    pub fn program_id() -> Pubkey {
        pubkey!("HooKchDVVKm7GkAX4w75bbaQUbMcDUnYXSzqLZCWKCDH")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AddToBlacklist
    // ....................................................................

    /// Main instruction struct for AddToBlacklist
    pub struct AddToBlacklistInstruction {
        pub accounts: AddToBlacklistInstructionAccountMetas,
        pub data: AddToBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AddToBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct AddToBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub blacklister_role: AccountMeta,

        pub mint: AccountMeta,

        pub address: AccountMeta,

        pub blacklist_entry: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AddToBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct AddToBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub blacklister_role: Pubkey,

        pub mint: Pubkey,

        pub address: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl AddToBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            blacklister_role: Pubkey,

            mint: Pubkey,

            address: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                blacklister_role,

                mint,

                address,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for AddToBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AddToBlacklistInstructionData {
        pub reason: String,
    }

    impl AddToBlacklistInstructionData {
        pub fn new(reason: String) -> Self {
            Self { reason }
        }
    }

    /// Implementation for AddToBlacklistInstruction
    impl AddToBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [90u8, 115u8, 98u8, 231u8, 173u8, 119u8, 117u8, 176u8]
        }

        pub fn data(data: AddToBlacklistInstructionData) -> Self {
            Self {
                accounts: AddToBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AddToBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.blacklister_role =
                AccountMeta::new_readonly(accounts.blacklister_role, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.address = AccountMeta::new_readonly(accounts.address, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.blacklister_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.address.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: InitializeExtraAccountMetas
    // ....................................................................

    /// Main instruction struct for InitializeExtraAccountMetas
    pub struct InitializeExtraAccountMetasInstruction {
        pub accounts: InitializeExtraAccountMetasInstructionAccountMetas,
        pub data: InitializeExtraAccountMetasInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for InitializeExtraAccountMetas instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeExtraAccountMetasInstructionAccountMetas {
        pub payer: AccountMeta,

        pub extra_account_metas: AccountMeta,

        pub mint: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for InitializeExtraAccountMetas instruction
    #[derive(Debug, Clone)]
    pub struct InitializeExtraAccountMetasInstructionAccounts {
        pub payer: Pubkey,

        pub extra_account_metas: Pubkey,

        pub mint: Pubkey,
    }

    impl InitializeExtraAccountMetasInstructionAccounts {
        pub fn new(payer: Pubkey, extra_account_metas: Pubkey, mint: Pubkey) -> Self {
            Self {
                payer,

                extra_account_metas,

                mint,
            }
        }
    }

    /// Instruction data for InitializeExtraAccountMetas
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeExtraAccountMetasInstructionData {}

    impl InitializeExtraAccountMetasInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for InitializeExtraAccountMetasInstruction
    impl InitializeExtraAccountMetasInstruction {
        fn discriminator() -> [u8; 8] {
            [22u8, 213u8, 130u8, 114u8, 1u8, 174u8, 121u8, 36u8]
        }

        pub fn data(data: InitializeExtraAccountMetasInstructionData) -> Self {
            Self {
                accounts: InitializeExtraAccountMetasInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(
            mut self,
            accounts: InitializeExtraAccountMetasInstructionAccounts,
        ) -> Self {
            self.accounts.payer = AccountMeta::new(accounts.payer, true);

            self.accounts.extra_account_metas =
                AccountMeta::new(accounts.extra_account_metas, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.payer.clone());

            metas.push(self.accounts.extra_account_metas.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RemoveFromBlacklist
    // ....................................................................

    /// Main instruction struct for RemoveFromBlacklist
    pub struct RemoveFromBlacklistInstruction {
        pub accounts: RemoveFromBlacklistInstructionAccountMetas,
        pub data: RemoveFromBlacklistInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RemoveFromBlacklist instruction
    #[derive(Debug, Clone, Default)]
    pub struct RemoveFromBlacklistInstructionAccountMetas {
        pub blacklister: AccountMeta,

        pub blacklister_role: AccountMeta,

        pub mint: AccountMeta,

        pub blacklist_entry: AccountMeta,
    }

    /// Account pubkeys for RemoveFromBlacklist instruction
    #[derive(Debug, Clone)]
    pub struct RemoveFromBlacklistInstructionAccounts {
        pub blacklister: Pubkey,

        pub blacklister_role: Pubkey,

        pub mint: Pubkey,

        pub blacklist_entry: Pubkey,
    }

    impl RemoveFromBlacklistInstructionAccounts {
        pub fn new(
            blacklister: Pubkey,

            blacklister_role: Pubkey,

            mint: Pubkey,

            blacklist_entry: Pubkey,
        ) -> Self {
            Self {
                blacklister,

                blacklister_role,

                mint,

                blacklist_entry,
            }
        }
    }

    /// Instruction data for RemoveFromBlacklist
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RemoveFromBlacklistInstructionData {}

    impl RemoveFromBlacklistInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RemoveFromBlacklistInstruction
    impl RemoveFromBlacklistInstruction {
        fn discriminator() -> [u8; 8] {
            [47u8, 105u8, 20u8, 10u8, 165u8, 168u8, 203u8, 219u8]
        }

        pub fn data(data: RemoveFromBlacklistInstructionData) -> Self {
            Self {
                accounts: RemoveFromBlacklistInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RemoveFromBlacklistInstructionAccounts) -> Self {
            self.accounts.blacklister = AccountMeta::new(accounts.blacklister, true);

            self.accounts.blacklister_role =
                AccountMeta::new_readonly(accounts.blacklister_role, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.blacklist_entry = AccountMeta::new(accounts.blacklist_entry, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.blacklister.clone());

            metas.push(self.accounts.blacklister_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.blacklist_entry.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: TransferHook
    // ....................................................................

    /// Main instruction struct for TransferHook
    pub struct TransferHookInstruction {
        pub accounts: TransferHookInstructionAccountMetas,
        pub data: TransferHookInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for TransferHook instruction
    #[derive(Debug, Clone, Default)]
    pub struct TransferHookInstructionAccountMetas {
        pub source: AccountMeta,

        pub mint: AccountMeta,

        pub destination: AccountMeta,

        pub authority: AccountMeta,

        pub extra_account_metas: AccountMeta,

        pub sender_blacklist: AccountMeta,

        pub receiver_blacklist: AccountMeta,
    }

    /// Account pubkeys for TransferHook instruction
    #[derive(Debug, Clone)]
    pub struct TransferHookInstructionAccounts {
        pub source: Pubkey,

        pub mint: Pubkey,

        pub destination: Pubkey,

        pub authority: Pubkey,

        pub extra_account_metas: Pubkey,

        pub sender_blacklist: Pubkey,

        pub receiver_blacklist: Pubkey,
    }

    impl TransferHookInstructionAccounts {
        pub fn new(
            source: Pubkey,

            mint: Pubkey,

            destination: Pubkey,

            authority: Pubkey,

            extra_account_metas: Pubkey,

            sender_blacklist: Pubkey,

            receiver_blacklist: Pubkey,
        ) -> Self {
            Self {
                source,

                mint,

                destination,

                authority,

                extra_account_metas,

                sender_blacklist,

                receiver_blacklist,
            }
        }
    }

    /// Instruction data for TransferHook
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct TransferHookInstructionData {
        pub amount: u64,
    }

    impl TransferHookInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for TransferHookInstruction
    impl TransferHookInstruction {
        fn discriminator() -> [u8; 8] {
            [220u8, 57u8, 220u8, 152u8, 126u8, 125u8, 97u8, 168u8]
        }

        pub fn data(data: TransferHookInstructionData) -> Self {
            Self {
                accounts: TransferHookInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: TransferHookInstructionAccounts) -> Self {
            self.accounts.source = AccountMeta::new_readonly(accounts.source, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.destination = AccountMeta::new_readonly(accounts.destination, false);

            self.accounts.authority = AccountMeta::new_readonly(accounts.authority, false);

            self.accounts.extra_account_metas =
                AccountMeta::new_readonly(accounts.extra_account_metas, false);

            self.accounts.sender_blacklist =
                AccountMeta::new_readonly(accounts.sender_blacklist, false);

            self.accounts.receiver_blacklist =
                AccountMeta::new_readonly(accounts.receiver_blacklist, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.source.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.destination.clone());

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.extra_account_metas.clone());

            metas.push(self.accounts.sender_blacklist.clone());

            metas.push(self.accounts.receiver_blacklist.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ----------------------------------------------------------------------------
// Program: sss_core
// ----------------------------------------------------------------------------
pub mod sss_core {
    use super::*;

    // ------------------------------------------------------------------------
    // Program ID
    // ------------------------------------------------------------------------

    /// Returns the program ID for sss_core
    pub fn program_id() -> Pubkey {
        pubkey!("CoREsjH41J3KezywbudJC4gHqCE1QhNWaXRbC1QjA9ei")
    }

    // ------------------------------------------------------------------------
    // Instructions
    // ------------------------------------------------------------------------

    // ....................................................................
    // Instruction: AcceptAuthority
    // ....................................................................

    /// Main instruction struct for AcceptAuthority
    pub struct AcceptAuthorityInstruction {
        pub accounts: AcceptAuthorityInstructionAccountMetas,
        pub data: AcceptAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for AcceptAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct AcceptAuthorityInstructionAccountMetas {
        pub new_authority: AccountMeta,

        pub old_authority: AccountMeta,

        pub config: AccountMeta,

        pub old_admin_role: AccountMeta,

        pub new_admin_role: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for AcceptAuthority instruction
    #[derive(Debug, Clone)]
    pub struct AcceptAuthorityInstructionAccounts {
        pub new_authority: Pubkey,

        pub old_authority: Pubkey,

        pub config: Pubkey,

        pub old_admin_role: Pubkey,

        pub new_admin_role: Pubkey,
    }

    impl AcceptAuthorityInstructionAccounts {
        pub fn new(
            new_authority: Pubkey,

            old_authority: Pubkey,

            config: Pubkey,

            old_admin_role: Pubkey,

            new_admin_role: Pubkey,
        ) -> Self {
            Self {
                new_authority,

                old_authority,

                config,

                old_admin_role,

                new_admin_role,
            }
        }
    }

    /// Instruction data for AcceptAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct AcceptAuthorityInstructionData {}

    impl AcceptAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for AcceptAuthorityInstruction
    impl AcceptAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [107u8, 86u8, 198u8, 91u8, 33u8, 12u8, 107u8, 160u8]
        }

        pub fn data(data: AcceptAuthorityInstructionData) -> Self {
            Self {
                accounts: AcceptAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: AcceptAuthorityInstructionAccounts) -> Self {
            self.accounts.new_authority = AccountMeta::new(accounts.new_authority, true);

            self.accounts.old_authority = AccountMeta::new(accounts.old_authority, false);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.old_admin_role = AccountMeta::new(accounts.old_admin_role, false);

            self.accounts.new_admin_role = AccountMeta::new(accounts.new_admin_role, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.new_authority.clone());

            metas.push(self.accounts.old_authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.old_admin_role.clone());

            metas.push(self.accounts.new_admin_role.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: BurnTokens
    // ....................................................................

    /// Main instruction struct for BurnTokens
    pub struct BurnTokensInstruction {
        pub accounts: BurnTokensInstructionAccountMetas,
        pub data: BurnTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for BurnTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct BurnTokensInstructionAccountMetas {
        pub burner: AccountMeta,

        pub config: AccountMeta,

        pub burner_role: AccountMeta,

        pub mint: AccountMeta,

        pub from: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for BurnTokens instruction
    #[derive(Debug, Clone)]
    pub struct BurnTokensInstructionAccounts {
        pub burner: Pubkey,

        pub config: Pubkey,

        pub burner_role: Pubkey,

        pub mint: Pubkey,

        pub from: Pubkey,

        pub token_program: Pubkey,
    }

    impl BurnTokensInstructionAccounts {
        pub fn new(
            burner: Pubkey,

            config: Pubkey,

            burner_role: Pubkey,

            mint: Pubkey,

            from: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                burner,

                config,

                burner_role,

                mint,

                from,

                token_program,
            }
        }
    }

    /// Instruction data for BurnTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct BurnTokensInstructionData {
        pub amount: u64,
    }

    impl BurnTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for BurnTokensInstruction
    impl BurnTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [76u8, 15u8, 51u8, 254u8, 229u8, 215u8, 121u8, 66u8]
        }

        pub fn data(data: BurnTokensInstructionData) -> Self {
            Self {
                accounts: BurnTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: BurnTokensInstructionAccounts) -> Self {
            self.accounts.burner = AccountMeta::new_readonly(accounts.burner, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.burner_role = AccountMeta::new_readonly(accounts.burner_role, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.burner.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.burner_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: FreezeAccount
    // ....................................................................

    /// Main instruction struct for FreezeAccount
    pub struct FreezeAccountInstruction {
        pub accounts: FreezeAccountInstructionAccountMetas,
        pub data: FreezeAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for FreezeAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct FreezeAccountInstructionAccountMetas {
        pub freezer: AccountMeta,

        pub config: AccountMeta,

        pub freezer_role: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for FreezeAccount instruction
    #[derive(Debug, Clone)]
    pub struct FreezeAccountInstructionAccounts {
        pub freezer: Pubkey,

        pub config: Pubkey,

        pub freezer_role: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl FreezeAccountInstructionAccounts {
        pub fn new(
            freezer: Pubkey,

            config: Pubkey,

            freezer_role: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                freezer,

                config,

                freezer_role,

                mint,

                token_account,

                token_program,
            }
        }
    }

    /// Instruction data for FreezeAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct FreezeAccountInstructionData {}

    impl FreezeAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for FreezeAccountInstruction
    impl FreezeAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [253u8, 75u8, 82u8, 133u8, 167u8, 238u8, 43u8, 130u8]
        }

        pub fn data(data: FreezeAccountInstructionData) -> Self {
            Self {
                accounts: FreezeAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: FreezeAccountInstructionAccounts) -> Self {
            self.accounts.freezer = AccountMeta::new_readonly(accounts.freezer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.freezer_role = AccountMeta::new_readonly(accounts.freezer_role, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.freezer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.freezer_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: GrantRole
    // ....................................................................

    /// Main instruction struct for GrantRole
    pub struct GrantRoleInstruction {
        pub accounts: GrantRoleInstructionAccountMetas,
        pub data: GrantRoleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for GrantRole instruction
    #[derive(Debug, Clone, Default)]
    pub struct GrantRoleInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,

        pub grantee: AccountMeta,

        pub role_account: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for GrantRole instruction
    #[derive(Debug, Clone)]
    pub struct GrantRoleInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,

        pub grantee: Pubkey,

        pub role_account: Pubkey,
    }

    impl GrantRoleInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_role: Pubkey,

            grantee: Pubkey,

            role_account: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_role,

                grantee,

                role_account,
            }
        }
    }

    /// Instruction data for GrantRole
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct GrantRoleInstructionData {
        pub role: u8,
    }

    impl GrantRoleInstructionData {
        pub fn new(role: u8) -> Self {
            Self { role }
        }
    }

    /// Implementation for GrantRoleInstruction
    impl GrantRoleInstruction {
        fn discriminator() -> [u8; 8] {
            [218u8, 234u8, 128u8, 15u8, 82u8, 33u8, 236u8, 253u8]
        }

        pub fn data(data: GrantRoleInstructionData) -> Self {
            Self {
                accounts: GrantRoleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: GrantRoleInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self.accounts.grantee = AccountMeta::new_readonly(accounts.grantee, false);

            self.accounts.role_account = AccountMeta::new(accounts.role_account, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.grantee.clone());

            metas.push(self.accounts.role_account.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Initialize
    // ....................................................................

    /// Main instruction struct for Initialize
    pub struct InitializeInstruction {
        pub accounts: InitializeInstructionAccountMetas,
        pub data: InitializeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Initialize instruction
    #[derive(Debug, Clone, Default)]
    pub struct InitializeInstructionAccountMetas {
        pub authority: AccountMeta,

        pub config: AccountMeta,

        pub mint: AccountMeta,

        pub admin_role: AccountMeta,

        pub token_program: AccountMeta,

        pub system_program: AccountMeta,
    }

    /// Account pubkeys for Initialize instruction
    #[derive(Debug, Clone)]
    pub struct InitializeInstructionAccounts {
        pub authority: Pubkey,

        pub config: Pubkey,

        pub mint: Pubkey,

        pub admin_role: Pubkey,

        pub token_program: Pubkey,
    }

    impl InitializeInstructionAccounts {
        pub fn new(
            authority: Pubkey,

            config: Pubkey,

            mint: Pubkey,

            admin_role: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                authority,

                config,

                mint,

                admin_role,

                token_program,
            }
        }
    }

    /// Instruction data for Initialize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct InitializeInstructionData {
        pub args: InitializeArgs,
    }

    impl InitializeInstructionData {
        pub fn new(args: InitializeArgs) -> Self {
            Self { args }
        }
    }

    /// Implementation for InitializeInstruction
    impl InitializeInstruction {
        fn discriminator() -> [u8; 8] {
            [175u8, 175u8, 109u8, 31u8, 13u8, 152u8, 155u8, 237u8]
        }

        pub fn data(data: InitializeInstructionData) -> Self {
            Self {
                accounts: InitializeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: InitializeInstructionAccounts) -> Self {
            self.accounts.authority = AccountMeta::new(accounts.authority, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.admin_role = AccountMeta::new(accounts.admin_role, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self.accounts.system_program =
                AccountMeta::new_readonly(pubkey!("11111111111111111111111111111111"), false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.authority.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.token_program.clone());

            metas.push(self.accounts.system_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: MintTokens
    // ....................................................................

    /// Main instruction struct for MintTokens
    pub struct MintTokensInstruction {
        pub accounts: MintTokensInstructionAccountMetas,
        pub data: MintTokensInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for MintTokens instruction
    #[derive(Debug, Clone, Default)]
    pub struct MintTokensInstructionAccountMetas {
        pub minter: AccountMeta,

        pub config: AccountMeta,

        pub minter_role: AccountMeta,

        pub mint: AccountMeta,

        pub to: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for MintTokens instruction
    #[derive(Debug, Clone)]
    pub struct MintTokensInstructionAccounts {
        pub minter: Pubkey,

        pub config: Pubkey,

        pub minter_role: Pubkey,

        pub mint: Pubkey,

        pub to: Pubkey,

        pub token_program: Pubkey,
    }

    impl MintTokensInstructionAccounts {
        pub fn new(
            minter: Pubkey,

            config: Pubkey,

            minter_role: Pubkey,

            mint: Pubkey,

            to: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                minter,

                config,

                minter_role,

                mint,

                to,

                token_program,
            }
        }
    }

    /// Instruction data for MintTokens
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct MintTokensInstructionData {
        pub amount: u64,
    }

    impl MintTokensInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for MintTokensInstruction
    impl MintTokensInstruction {
        fn discriminator() -> [u8; 8] {
            [59u8, 132u8, 24u8, 246u8, 122u8, 39u8, 8u8, 243u8]
        }

        pub fn data(data: MintTokensInstructionData) -> Self {
            Self {
                accounts: MintTokensInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: MintTokensInstructionAccounts) -> Self {
            self.accounts.minter = AccountMeta::new_readonly(accounts.minter, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.minter_role = AccountMeta::new(accounts.minter_role, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.minter.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.minter_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Pause
    // ....................................................................

    /// Main instruction struct for Pause
    pub struct PauseInstruction {
        pub accounts: PauseInstructionAccountMetas,
        pub data: PauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Pause instruction
    #[derive(Debug, Clone, Default)]
    pub struct PauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,

        pub pauser_role: AccountMeta,
    }

    /// Account pubkeys for Pause instruction
    #[derive(Debug, Clone)]
    pub struct PauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,

        pub pauser_role: Pubkey,
    }

    impl PauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey, pauser_role: Pubkey) -> Self {
            Self {
                pauser,

                config,

                pauser_role,
            }
        }
    }

    /// Instruction data for Pause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct PauseInstructionData {}

    impl PauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for PauseInstruction
    impl PauseInstruction {
        fn discriminator() -> [u8; 8] {
            [211u8, 22u8, 221u8, 251u8, 74u8, 121u8, 193u8, 47u8]
        }

        pub fn data(data: PauseInstructionData) -> Self {
            Self {
                accounts: PauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: PauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.pauser_role = AccountMeta::new_readonly(accounts.pauser_role, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.pauser_role.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ProposeAuthority
    // ....................................................................

    /// Main instruction struct for ProposeAuthority
    pub struct ProposeAuthorityInstruction {
        pub accounts: ProposeAuthorityInstructionAccountMetas,
        pub data: ProposeAuthorityInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ProposeAuthority instruction
    #[derive(Debug, Clone, Default)]
    pub struct ProposeAuthorityInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,

        pub new_authority: AccountMeta,
    }

    /// Account pubkeys for ProposeAuthority instruction
    #[derive(Debug, Clone)]
    pub struct ProposeAuthorityInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,

        pub new_authority: Pubkey,
    }

    impl ProposeAuthorityInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_role: Pubkey,

            new_authority: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_role,

                new_authority,
            }
        }
    }

    /// Instruction data for ProposeAuthority
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ProposeAuthorityInstructionData {}

    impl ProposeAuthorityInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ProposeAuthorityInstruction
    impl ProposeAuthorityInstruction {
        fn discriminator() -> [u8; 8] {
            [20u8, 148u8, 236u8, 198u8, 76u8, 119u8, 99u8, 142u8]
        }

        pub fn data(data: ProposeAuthorityInstructionData) -> Self {
            Self {
                accounts: ProposeAuthorityInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ProposeAuthorityInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self.accounts.new_authority = AccountMeta::new_readonly(accounts.new_authority, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.new_authority.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: RevokeRole
    // ....................................................................

    /// Main instruction struct for RevokeRole
    pub struct RevokeRoleInstruction {
        pub accounts: RevokeRoleInstructionAccountMetas,
        pub data: RevokeRoleInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for RevokeRole instruction
    #[derive(Debug, Clone, Default)]
    pub struct RevokeRoleInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,

        pub role_account: AccountMeta,
    }

    /// Account pubkeys for RevokeRole instruction
    #[derive(Debug, Clone)]
    pub struct RevokeRoleInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,

        pub role_account: Pubkey,
    }

    impl RevokeRoleInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_role: Pubkey,

            role_account: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_role,

                role_account,
            }
        }
    }

    /// Instruction data for RevokeRole
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct RevokeRoleInstructionData {}

    impl RevokeRoleInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for RevokeRoleInstruction
    impl RevokeRoleInstruction {
        fn discriminator() -> [u8; 8] {
            [179u8, 232u8, 2u8, 180u8, 48u8, 227u8, 82u8, 7u8]
        }

        pub fn data(data: RevokeRoleInstructionData) -> Self {
            Self {
                accounts: RevokeRoleInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: RevokeRoleInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self.accounts.role_account = AccountMeta::new(accounts.role_account, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.role_account.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Seize
    // ....................................................................

    /// Main instruction struct for Seize
    pub struct SeizeInstruction {
        pub accounts: SeizeInstructionAccountMetas,
        pub data: SeizeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Seize instruction
    #[derive(Debug, Clone, Default)]
    pub struct SeizeInstructionAccountMetas {
        pub seizer: AccountMeta,

        pub config: AccountMeta,

        pub seizer_role: AccountMeta,

        pub mint: AccountMeta,

        pub from: AccountMeta,

        pub to: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for Seize instruction
    #[derive(Debug, Clone)]
    pub struct SeizeInstructionAccounts {
        pub seizer: Pubkey,

        pub config: Pubkey,

        pub seizer_role: Pubkey,

        pub mint: Pubkey,

        pub from: Pubkey,

        pub to: Pubkey,

        pub token_program: Pubkey,
    }

    impl SeizeInstructionAccounts {
        pub fn new(
            seizer: Pubkey,

            config: Pubkey,

            seizer_role: Pubkey,

            mint: Pubkey,

            from: Pubkey,

            to: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                seizer,

                config,

                seizer_role,

                mint,

                from,

                to,

                token_program,
            }
        }
    }

    /// Instruction data for Seize
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct SeizeInstructionData {
        pub amount: u64,
    }

    impl SeizeInstructionData {
        pub fn new(amount: u64) -> Self {
            Self { amount }
        }
    }

    /// Implementation for SeizeInstruction
    impl SeizeInstruction {
        fn discriminator() -> [u8; 8] {
            [129u8, 159u8, 143u8, 31u8, 161u8, 224u8, 241u8, 84u8]
        }

        pub fn data(data: SeizeInstructionData) -> Self {
            Self {
                accounts: SeizeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: SeizeInstructionAccounts) -> Self {
            self.accounts.seizer = AccountMeta::new_readonly(accounts.seizer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.seizer_role = AccountMeta::new_readonly(accounts.seizer_role, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.from = AccountMeta::new(accounts.from, false);

            self.accounts.to = AccountMeta::new(accounts.to, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.seizer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.seizer_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.from.clone());

            metas.push(self.accounts.to.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: ThawAccount
    // ....................................................................

    /// Main instruction struct for ThawAccount
    pub struct ThawAccountInstruction {
        pub accounts: ThawAccountInstructionAccountMetas,
        pub data: ThawAccountInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for ThawAccount instruction
    #[derive(Debug, Clone, Default)]
    pub struct ThawAccountInstructionAccountMetas {
        pub freezer: AccountMeta,

        pub config: AccountMeta,

        pub freezer_role: AccountMeta,

        pub mint: AccountMeta,

        pub token_account: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for ThawAccount instruction
    #[derive(Debug, Clone)]
    pub struct ThawAccountInstructionAccounts {
        pub freezer: Pubkey,

        pub config: Pubkey,

        pub freezer_role: Pubkey,

        pub mint: Pubkey,

        pub token_account: Pubkey,

        pub token_program: Pubkey,
    }

    impl ThawAccountInstructionAccounts {
        pub fn new(
            freezer: Pubkey,

            config: Pubkey,

            freezer_role: Pubkey,

            mint: Pubkey,

            token_account: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                freezer,

                config,

                freezer_role,

                mint,

                token_account,

                token_program,
            }
        }
    }

    /// Instruction data for ThawAccount
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct ThawAccountInstructionData {}

    impl ThawAccountInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for ThawAccountInstruction
    impl ThawAccountInstruction {
        fn discriminator() -> [u8; 8] {
            [115u8, 152u8, 79u8, 213u8, 213u8, 169u8, 184u8, 35u8]
        }

        pub fn data(data: ThawAccountInstructionData) -> Self {
            Self {
                accounts: ThawAccountInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: ThawAccountInstructionAccounts) -> Self {
            self.accounts.freezer = AccountMeta::new_readonly(accounts.freezer, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.freezer_role = AccountMeta::new_readonly(accounts.freezer_role, false);

            self.accounts.mint = AccountMeta::new_readonly(accounts.mint, false);

            self.accounts.token_account = AccountMeta::new(accounts.token_account, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.freezer.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.freezer_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_account.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: Unpause
    // ....................................................................

    /// Main instruction struct for Unpause
    pub struct UnpauseInstruction {
        pub accounts: UnpauseInstructionAccountMetas,
        pub data: UnpauseInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for Unpause instruction
    #[derive(Debug, Clone, Default)]
    pub struct UnpauseInstructionAccountMetas {
        pub pauser: AccountMeta,

        pub config: AccountMeta,

        pub pauser_role: AccountMeta,
    }

    /// Account pubkeys for Unpause instruction
    #[derive(Debug, Clone)]
    pub struct UnpauseInstructionAccounts {
        pub pauser: Pubkey,

        pub config: Pubkey,

        pub pauser_role: Pubkey,
    }

    impl UnpauseInstructionAccounts {
        pub fn new(pauser: Pubkey, config: Pubkey, pauser_role: Pubkey) -> Self {
            Self {
                pauser,

                config,

                pauser_role,
            }
        }
    }

    /// Instruction data for Unpause
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UnpauseInstructionData {}

    impl UnpauseInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for UnpauseInstruction
    impl UnpauseInstruction {
        fn discriminator() -> [u8; 8] {
            [169u8, 144u8, 4u8, 38u8, 10u8, 141u8, 188u8, 255u8]
        }

        pub fn data(data: UnpauseInstructionData) -> Self {
            Self {
                accounts: UnpauseInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UnpauseInstructionAccounts) -> Self {
            self.accounts.pauser = AccountMeta::new_readonly(accounts.pauser, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.pauser_role = AccountMeta::new_readonly(accounts.pauser_role, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.pauser.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.pauser_role.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateMinter
    // ....................................................................

    /// Main instruction struct for UpdateMinter
    pub struct UpdateMinterInstruction {
        pub accounts: UpdateMinterInstructionAccountMetas,
        pub data: UpdateMinterInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateMinter instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateMinterInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,

        pub minter_role: AccountMeta,
    }

    /// Account pubkeys for UpdateMinter instruction
    #[derive(Debug, Clone)]
    pub struct UpdateMinterInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,

        pub minter_role: Pubkey,
    }

    impl UpdateMinterInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey, admin_role: Pubkey, minter_role: Pubkey) -> Self {
            Self {
                admin,

                config,

                admin_role,

                minter_role,
            }
        }
    }

    /// Instruction data for UpdateMinter
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateMinterInstructionData {
        pub new_quota: Option<u64>,
    }

    impl UpdateMinterInstructionData {
        pub fn new(new_quota: Option<u64>) -> Self {
            Self { new_quota }
        }
    }

    /// Implementation for UpdateMinterInstruction
    impl UpdateMinterInstruction {
        fn discriminator() -> [u8; 8] {
            [164u8, 129u8, 164u8, 88u8, 75u8, 29u8, 91u8, 38u8]
        }

        pub fn data(data: UpdateMinterInstructionData) -> Self {
            Self {
                accounts: UpdateMinterInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateMinterInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self.accounts.minter_role = AccountMeta::new(accounts.minter_role, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.minter_role.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateSupplyCap
    // ....................................................................

    /// Main instruction struct for UpdateSupplyCap
    pub struct UpdateSupplyCapInstruction {
        pub accounts: UpdateSupplyCapInstructionAccountMetas,
        pub data: UpdateSupplyCapInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateSupplyCap instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateSupplyCapInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,
    }

    /// Account pubkeys for UpdateSupplyCap instruction
    #[derive(Debug, Clone)]
    pub struct UpdateSupplyCapInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,
    }

    impl UpdateSupplyCapInstructionAccounts {
        pub fn new(admin: Pubkey, config: Pubkey, admin_role: Pubkey) -> Self {
            Self {
                admin,

                config,

                admin_role,
            }
        }
    }

    /// Instruction data for UpdateSupplyCap
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateSupplyCapInstructionData {
        pub new_supply_cap: Option<u64>,
    }

    impl UpdateSupplyCapInstructionData {
        pub fn new(new_supply_cap: Option<u64>) -> Self {
            Self { new_supply_cap }
        }
    }

    /// Implementation for UpdateSupplyCapInstruction
    impl UpdateSupplyCapInstruction {
        fn discriminator() -> [u8; 8] {
            [9u8, 215u8, 52u8, 77u8, 1u8, 9u8, 162u8, 17u8]
        }

        pub fn data(data: UpdateSupplyCapInstructionData) -> Self {
            Self {
                accounts: UpdateSupplyCapInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateSupplyCapInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: UpdateTransferFee
    // ....................................................................

    /// Main instruction struct for UpdateTransferFee
    pub struct UpdateTransferFeeInstruction {
        pub accounts: UpdateTransferFeeInstructionAccountMetas,
        pub data: UpdateTransferFeeInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for UpdateTransferFee instruction
    #[derive(Debug, Clone, Default)]
    pub struct UpdateTransferFeeInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,

        pub mint: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for UpdateTransferFee instruction
    #[derive(Debug, Clone)]
    pub struct UpdateTransferFeeInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,

        pub mint: Pubkey,

        pub token_program: Pubkey,
    }

    impl UpdateTransferFeeInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_role: Pubkey,

            mint: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_role,

                mint,

                token_program,
            }
        }
    }

    /// Instruction data for UpdateTransferFee
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct UpdateTransferFeeInstructionData {
        pub new_basis_points: u16,

        pub new_maximum_fee: u64,
    }

    impl UpdateTransferFeeInstructionData {
        pub fn new(new_basis_points: u16, new_maximum_fee: u64) -> Self {
            Self {
                new_basis_points,

                new_maximum_fee,
            }
        }
    }

    /// Implementation for UpdateTransferFeeInstruction
    impl UpdateTransferFeeInstruction {
        fn discriminator() -> [u8; 8] {
            [135u8, 106u8, 57u8, 77u8, 93u8, 247u8, 210u8, 158u8]
        }

        pub fn data(data: UpdateTransferFeeInstructionData) -> Self {
            Self {
                accounts: UpdateTransferFeeInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: UpdateTransferFeeInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ....................................................................
    // Instruction: WithdrawWithheld
    // ....................................................................

    /// Main instruction struct for WithdrawWithheld
    pub struct WithdrawWithheldInstruction {
        pub accounts: WithdrawWithheldInstructionAccountMetas,
        pub data: WithdrawWithheldInstructionData,
        pub remaining_accounts: Vec<AccountMeta>,
    }

    /// Account metadata for WithdrawWithheld instruction
    #[derive(Debug, Clone, Default)]
    pub struct WithdrawWithheldInstructionAccountMetas {
        pub admin: AccountMeta,

        pub config: AccountMeta,

        pub admin_role: AccountMeta,

        pub mint: AccountMeta,

        pub fee_destination: AccountMeta,

        pub token_program: AccountMeta,
    }

    /// Account pubkeys for WithdrawWithheld instruction
    #[derive(Debug, Clone)]
    pub struct WithdrawWithheldInstructionAccounts {
        pub admin: Pubkey,

        pub config: Pubkey,

        pub admin_role: Pubkey,

        pub mint: Pubkey,

        pub fee_destination: Pubkey,

        pub token_program: Pubkey,
    }

    impl WithdrawWithheldInstructionAccounts {
        pub fn new(
            admin: Pubkey,

            config: Pubkey,

            admin_role: Pubkey,

            mint: Pubkey,

            fee_destination: Pubkey,

            token_program: Pubkey,
        ) -> Self {
            Self {
                admin,

                config,

                admin_role,

                mint,

                fee_destination,

                token_program,
            }
        }
    }

    /// Instruction data for WithdrawWithheld
    #[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
    pub struct WithdrawWithheldInstructionData {}

    impl WithdrawWithheldInstructionData {
        pub fn new() -> Self {
            Self {}
        }
    }

    /// Implementation for WithdrawWithheldInstruction
    impl WithdrawWithheldInstruction {
        fn discriminator() -> [u8; 8] {
            [102u8, 28u8, 32u8, 66u8, 152u8, 119u8, 206u8, 241u8]
        }

        pub fn data(data: WithdrawWithheldInstructionData) -> Self {
            Self {
                accounts: WithdrawWithheldInstructionAccountMetas::default(),
                data,
                remaining_accounts: Vec::new(),
            }
        }

        pub fn accounts(mut self, accounts: WithdrawWithheldInstructionAccounts) -> Self {
            self.accounts.admin = AccountMeta::new_readonly(accounts.admin, true);

            self.accounts.config = AccountMeta::new_readonly(accounts.config, false);

            self.accounts.admin_role = AccountMeta::new_readonly(accounts.admin_role, false);

            self.accounts.mint = AccountMeta::new(accounts.mint, false);

            self.accounts.fee_destination = AccountMeta::new(accounts.fee_destination, false);

            self.accounts.token_program = AccountMeta::new_readonly(accounts.token_program, false);

            self
        }

        pub fn remaining_accounts(mut self, accounts: Vec<AccountMeta>) -> Self {
            self.remaining_accounts = accounts;
            self
        }

        fn to_account_metas(&self) -> Vec<AccountMeta> {
            let mut metas = Vec::new();

            metas.push(self.accounts.admin.clone());

            metas.push(self.accounts.config.clone());

            metas.push(self.accounts.admin_role.clone());

            metas.push(self.accounts.mint.clone());

            metas.push(self.accounts.fee_destination.clone());

            metas.push(self.accounts.token_program.clone());

            metas.extend(self.remaining_accounts.clone());
            metas
        }

        pub fn instruction(&self) -> Instruction {
            let mut buffer: Vec<u8> = Vec::new();

            buffer.extend_from_slice(&Self::discriminator());

            self.data.serialize(&mut buffer).unwrap();

            Instruction::new_with_bytes(program_id(), &buffer, self.to_account_metas())
        }
    }

    // ------------------------------------------------------------------------
    // Composite Accounts
    // ------------------------------------------------------------------------
}

// ============================================================================
// CUSTOM TYPES
// ============================================================================

/// Custom struct: BlacklistAdded
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistAdded {
    pub mint: Pubkey,

    pub address: Pubkey,

    pub added_by: Pubkey,

    pub added_at: i64,

    pub reason: String,
}

impl BlacklistAdded {
    pub fn new(
        mint: Pubkey,

        address: Pubkey,

        added_by: Pubkey,

        added_at: i64,

        reason: String,
    ) -> Self {
        Self {
            mint,

            address,

            added_by,

            added_at,

            reason,
        }
    }
}

/// Custom struct: BlacklistEntry
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistEntry {
    pub mint: Pubkey,

    pub address: Pubkey,

    pub added_by: Pubkey,

    pub added_at: i64,

    pub reason: String,

    pub bump: u8,
}

impl BlacklistEntry {
    pub fn new(
        mint: Pubkey,

        address: Pubkey,

        added_by: Pubkey,

        added_at: i64,

        reason: String,

        bump: u8,
    ) -> Self {
        Self {
            mint,

            address,

            added_by,

            added_at,

            reason,

            bump,
        }
    }
}

/// Custom struct: BlacklistRemoved
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct BlacklistRemoved {
    pub mint: Pubkey,

    pub address: Pubkey,

    pub removed_by: Pubkey,
}

impl BlacklistRemoved {
    pub fn new(mint: Pubkey, address: Pubkey, removed_by: Pubkey) -> Self {
        Self {
            mint,

            address,

            removed_by,
        }
    }
}

/// Custom struct: AccountFrozen
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountFrozen {
    pub mint: Pubkey,

    pub account: Pubkey,

    pub freezer: Pubkey,
}

impl AccountFrozen {
    pub fn new(mint: Pubkey, account: Pubkey, freezer: Pubkey) -> Self {
        Self {
            mint,

            account,

            freezer,
        }
    }
}

/// Custom struct: AccountThawed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AccountThawed {
    pub mint: Pubkey,

    pub account: Pubkey,

    pub freezer: Pubkey,
}

impl AccountThawed {
    pub fn new(mint: Pubkey, account: Pubkey, freezer: Pubkey) -> Self {
        Self {
            mint,

            account,

            freezer,
        }
    }
}

/// Custom struct: AuthorityProposed
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityProposed {
    pub config: Pubkey,

    pub from: Pubkey,

    pub proposed: Pubkey,
}

impl AuthorityProposed {
    pub fn new(config: Pubkey, from: Pubkey, proposed: Pubkey) -> Self {
        Self {
            config,

            from,

            proposed,
        }
    }
}

/// Custom struct: AuthorityTransferred
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct AuthorityTransferred {
    pub config: Pubkey,

    pub from: Pubkey,

    pub to: Pubkey,
}

impl AuthorityTransferred {
    pub fn new(config: Pubkey, from: Pubkey, to: Pubkey) -> Self {
        Self { config, from, to }
    }
}

/// Custom struct: ConfigUpdated
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct ConfigUpdated {
    pub config: Pubkey,

    pub field: String,

    pub updater: Pubkey,
}

impl ConfigUpdated {
    pub fn new(config: Pubkey, field: String, updater: Pubkey) -> Self {
        Self {
            config,

            field,

            updater,
        }
    }
}

/// Custom struct: InitializeArgs
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct InitializeArgs {
    pub preset: u8,

    pub name: String,

    pub symbol: String,

    pub uri: String,

    pub decimals: u8,

    pub supply_cap: Option<u64>,

    pub enable_permanent_delegate: Option<bool>,

    pub enable_transfer_hook: Option<bool>,

    pub default_account_frozen: Option<bool>,

    pub oracle_feed_id: Option<[u8; 32]>,

    pub transfer_fee_basis_points: Option<u16>,

    pub maximum_fee: Option<u64>,
}

impl InitializeArgs {
    pub fn new(
        preset: u8,

        name: String,

        symbol: String,

        uri: String,

        decimals: u8,

        supply_cap: Option<u64>,

        enable_permanent_delegate: Option<bool>,

        enable_transfer_hook: Option<bool>,

        default_account_frozen: Option<bool>,

        oracle_feed_id: Option<[u8; 32]>,

        transfer_fee_basis_points: Option<u16>,

        maximum_fee: Option<u64>,
    ) -> Self {
        Self {
            preset,

            name,

            symbol,

            uri,

            decimals,

            supply_cap,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            oracle_feed_id,

            transfer_fee_basis_points,

            maximum_fee,
        }
    }
}

/// Custom struct: OperationsPaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OperationsPaused {
    pub mint: Pubkey,

    pub pauser: Pubkey,
}

impl OperationsPaused {
    pub fn new(mint: Pubkey, pauser: Pubkey) -> Self {
        Self { mint, pauser }
    }
}

/// Custom struct: OperationsUnpaused
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct OperationsUnpaused {
    pub mint: Pubkey,

    pub pauser: Pubkey,
}

impl OperationsUnpaused {
    pub fn new(mint: Pubkey, pauser: Pubkey) -> Self {
        Self { mint, pauser }
    }
}

/// Custom enum: Role
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub enum Role {
    Admin,

    Minter,

    Freezer,

    Pauser,

    Burner,

    Blacklister,

    Seizer,
}

/// Custom struct: RoleAccount
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleAccount {
    pub config: Pubkey,

    pub address: Pubkey,

    pub role: Role,

    pub granted_by: Pubkey,

    pub granted_at: i64,

    pub bump: u8,

    pub mint_quota: Option<u64>,

    pub amount_minted: u64,
}

impl RoleAccount {
    pub fn new(
        config: Pubkey,

        address: Pubkey,

        role: Role,

        granted_by: Pubkey,

        granted_at: i64,

        bump: u8,

        mint_quota: Option<u64>,

        amount_minted: u64,
    ) -> Self {
        Self {
            config,

            address,

            role,

            granted_by,

            granted_at,

            bump,

            mint_quota,

            amount_minted,
        }
    }
}

/// Custom struct: RoleGranted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleGranted {
    pub config: Pubkey,

    pub address: Pubkey,

    pub role: u8,

    pub granted_by: Pubkey,
}

impl RoleGranted {
    pub fn new(config: Pubkey, address: Pubkey, role: u8, granted_by: Pubkey) -> Self {
        Self {
            config,

            address,

            role,

            granted_by,
        }
    }
}

/// Custom struct: RoleRevoked
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct RoleRevoked {
    pub config: Pubkey,

    pub address: Pubkey,

    pub role: u8,

    pub revoked_by: Pubkey,
}

impl RoleRevoked {
    pub fn new(config: Pubkey, address: Pubkey, role: u8, revoked_by: Pubkey) -> Self {
        Self {
            config,

            address,

            role,

            revoked_by,
        }
    }
}

/// Custom struct: StablecoinConfig
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinConfig {
    pub authority: Pubkey,

    pub mint: Pubkey,

    pub preset: u8,

    pub paused: u8,

    pub has_supply_cap: u8,

    pub supply_cap: u64,

    pub total_minted: u64,

    pub total_burned: u64,

    pub bump: u8,

    pub name: [u8; 32],

    pub symbol: [u8; 10],

    pub uri: [u8; 200],

    pub decimals: u8,

    pub enable_permanent_delegate: u8,

    pub enable_transfer_hook: u8,

    pub default_account_frozen: u8,

    pub admin_count: u16,

    pub has_oracle_feed: u8,

    pub oracle_feed_id: [u8; 32],

    pub transfer_fee_basis_points: u16,

    pub maximum_fee: u64,

    pub has_pending_authority: u8,

    pub pending_authority: Pubkey,

    pub _reserved: [u8; 31],
}

impl StablecoinConfig {
    pub fn new(
        authority: Pubkey,

        mint: Pubkey,

        preset: u8,

        paused: u8,

        has_supply_cap: u8,

        supply_cap: u64,

        total_minted: u64,

        total_burned: u64,

        bump: u8,

        name: [u8; 32],

        symbol: [u8; 10],

        uri: [u8; 200],

        decimals: u8,

        enable_permanent_delegate: u8,

        enable_transfer_hook: u8,

        default_account_frozen: u8,

        admin_count: u16,

        has_oracle_feed: u8,

        oracle_feed_id: [u8; 32],

        transfer_fee_basis_points: u16,

        maximum_fee: u64,

        has_pending_authority: u8,

        pending_authority: Pubkey,

        _reserved: [u8; 31],
    ) -> Self {
        Self {
            authority,

            mint,

            preset,

            paused,

            has_supply_cap,

            supply_cap,

            total_minted,

            total_burned,

            bump,

            name,

            symbol,

            uri,

            decimals,

            enable_permanent_delegate,

            enable_transfer_hook,

            default_account_frozen,

            admin_count,

            has_oracle_feed,

            oracle_feed_id,

            transfer_fee_basis_points,

            maximum_fee,

            has_pending_authority,

            pending_authority,

            _reserved,
        }
    }
}

/// Custom struct: StablecoinInitialized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct StablecoinInitialized {
    pub mint: Pubkey,

    pub authority: Pubkey,

    pub preset: u8,

    pub supply_cap: Option<u64>,

    pub name: String,

    pub symbol: String,

    pub decimals: u8,
}

impl StablecoinInitialized {
    pub fn new(
        mint: Pubkey,

        authority: Pubkey,

        preset: u8,

        supply_cap: Option<u64>,

        name: String,

        symbol: String,

        decimals: u8,
    ) -> Self {
        Self {
            mint,

            authority,

            preset,

            supply_cap,

            name,

            symbol,

            decimals,
        }
    }
}

/// Custom struct: TokensBurned
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensBurned {
    pub mint: Pubkey,

    pub from: Pubkey,

    pub from_owner: Pubkey,

    pub amount: u64,

    pub burner: Pubkey,

    pub new_supply: u64,
}

impl TokensBurned {
    pub fn new(
        mint: Pubkey,

        from: Pubkey,

        from_owner: Pubkey,

        amount: u64,

        burner: Pubkey,

        new_supply: u64,
    ) -> Self {
        Self {
            mint,

            from,

            from_owner,

            amount,

            burner,

            new_supply,
        }
    }
}

/// Custom struct: TokensMinted
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensMinted {
    pub mint: Pubkey,

    pub to: Pubkey,

    pub amount: u64,

    pub minter: Pubkey,

    pub new_supply: u64,
}

impl TokensMinted {
    pub fn new(mint: Pubkey, to: Pubkey, amount: u64, minter: Pubkey, new_supply: u64) -> Self {
        Self {
            mint,

            to,

            amount,

            minter,

            new_supply,
        }
    }
}

/// Custom struct: TokensSeized
#[derive(Debug, BorshDeserialize, BorshSerialize, Clone)]
pub struct TokensSeized {
    pub mint: Pubkey,

    pub from: Pubkey,

    pub to: Pubkey,

    pub amount: u64,

    pub seizer: Pubkey,
}

impl TokensSeized {
    pub fn new(mint: Pubkey, from: Pubkey, to: Pubkey, amount: u64, seizer: Pubkey) -> Self {
        Self {
            mint,

            from,

            to,

            amount,

            seizer,
        }
    }
}

// ============================================================================
// END OF GENERATED FILE
// ============================================================================
